name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"
      - name: Update Blog Lists
        run: |
          pip install requests
          python gen.py
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          empty: false
          branch: 'master'
          github_token: ${{ secrets.GITHUB_TOKEN }}
