name: update
on:
  workflow_dispatch:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"
      - name: Update Blog Lists
        run: |
          pip install requests
          python gen.py
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "main"
          commit_options: "--no-verify --signoff"
          github_token: ${{ secrets.GITHUB_TOKEN }}
