name: update
on:
  workflow_dispatch:
  schedule: [{ cron: "0 * * * *" }]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install
      - name: Update Blog Lists
        run: |
          uv sync
          uv run gen.py
      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: "main"
          commit_options: "--no-verify --signoff"
          github_token: ${{ secrets.GITHUB_TOKEN }}
